"""empty message

Revision ID: 63da1af1ada2
Revises: 
Create Date: 2023-02-12 22:31:14.009745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63da1af1ada2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Modeles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Modeles')
    # ### end Alembic commands ###
